// Generated by CoffeeScript 1.3.1
var app, express, routes;

express = require("express");

routes = require("./routes");

app = module.exports = express.createServer();

app.configure(function() {
  app.set("views", __dirname + "/views");
  app.set("view engine", "hbs");
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express.cookieParser());
  app.use(express.session({
    secret: "your secret here"
  }));
  app.use(app.router);
  return app.use(express["static"](__dirname + "/public"));
});

app.configure("development", function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure("production", function() {
  return app.use(express.errorHandler());
});

app.get("/", routes.page);

app.get("/:pageName", routes.page);

app.listen(3000);

console.log("Express server listening on port %d in %s mode", app.address().port, app.settings.env);
