// Generated by CoffeeScript 1.3.1

exports.page = function(req, res) {
  var pageName, _ref, _ref1;
  pageName = (_ref = (req != null ? (_ref1 = req.params) != null ? _ref1.pageName : void 0 : void 0)) != null ? _ref : "front";
  return res.render("pages/" + pageName, {
    title: "opening"
  });
};
